{
 "title": "Copilot Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Org",
    "label": "Orgnisation",
    "query": {
     "query": "label_values(total_active_users,org)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Daily Active Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(total_active_users[$__range])",
     "legendFormat": "{{org}}"
    }
   ]
  },
  {
   "title": "Average Daily Active Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(total_active_users[$__range])",
     "legendFormat": "{{org}}"
    }
   ]
  },
  {
   "title": "Total Acceptance Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_code_acceptances/total_code_suggestions) by (org)",
     "legendFormat": "{{org}}"
    }
   ]
  },
  {
   "title": "Total Acceptance Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "sum(total_code_acceptances/total_code_suggestions) by (org)",
     "legendFormat": "{{org}}"
    }
   ]
  },
  {
   "title": "Exporter Stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "copilot_exporter_github_api_requests_total ",
       "legendFormat": "Number of GitHub API Calls"
      },
      {
       "expr": "copilot_exporter_requests_total ",
       "legendFormat": "How many times exporter Called"
      },
      {
       "expr": "copilot_exporter_cache_hits_total ",
       "legendFormat": "Cache Hit"
      }
     ]
    },
    {
     "title": "Total Acceptance Rate(Line)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(total_code_lines_accepted/total_code_lines_suggested) by (org)",
       "legendFormat": "{{org}}"
      }
     ]
    }
   ]
  }
 ]
}